seed: 1
num_worker: 4
work_dir: ./work_dir/ntu/cs/SkateFormer_j/

phase: train

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: autodl-tmp/competition/data/up_joint.npy
  label_path: autodl-tmp/competition/data/up_labels.npy
  split: train
  data_type: ja
  debug: False
  window_size: 256
  p_interval: [0.5, 1]
  aug_method: a123489
  intra_p: 0.5
  inter_p: 0.2
  thres: 256
  uniform: True
  partition: False

test_feeder_args:
  data_path: autodl-tmp/competition/data/test_joint.npy
  label_path: autodl-tmp/competition/data/fake_lables.npy
  split: test
  data_type: ja
  window_size: 256
  p_interval: [0.95]
  thres: 256
  uniform: True
  partition: False
  debug: False

# model
model: model.SkateFormer.SkateFormer_
model_args:
  in_channels: 9
  num_classes: 155
  num_people: 2
  num_points: 17
  kernel_size: 7
  num_heads: 32
  attn_drop: 0.5
  head_drop: 0.0
  rel: True
  drop_path: 0.2
  type_1_size: [16, 17]
  type_2_size: [16, 2]
  type_3_size: [16, 17]
  type_4_size: [16, 2]
  mlp_ratio: 4.0
  index_t: True

#optim
optimizer: AdamW
weight_decay: 0.1
lr_scheduler: cosine
base_lr: 1e-3
min_lr: 1e-5
warmup_lr: 1e-7
warmup_prefix: True
warm_up_epoch: 25

# training
device: [0]
batch_size: 32
test_batch_size: 32
num_epoch: 500
nesterov: True
grad_clip: True
grad_max: 1.0
loss_type: LSCE
